import Sidebar from "@/components/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Cooperative",
    description: "Generated by create next app",
  };
  
  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body
        //   className={`${geistSans.variable} ${geistMono.variable} antialiased   `}
        >
        
            <Sidebar/>
            <main className=" h-full shadow-sm ml-[250px]">
              {children}
            </main>
        </body>
      </html>
    );
  }